"""add workout models

Revision ID: 6d2b7f766336
Revises: 70edf587c2b8
Create Date: 2026-08-27 13:52:22.668857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d2b7f766336'
down_revision: Union[str, Sequence[str], None] = '70edf587c2b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('primary_muscle', sa.String(), nullable=False),
    sa.Column('secondary_muscles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('equipment', sa.Enum('barbell', 'dumbbell', 'bodyweight', 'cable', 'machine', 'kettlebell', 'bands', 'none', name='equipment_enum'), nullable=False),
    sa.Column('difficulty', sa.Enum('beginner', 'intermediate', 'advanced', name='difficulty_enum'), nullable=False),
    sa.Column('instructions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gif_url', sa.String(), nullable=True),
    sa.Column('calories_per_minute_est', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_id'), 'exercises', ['id'], unique=False)
    op.create_index(op.f('ix_exercises_name'), 'exercises', ['name'], unique=True)
    op.create_index(op.f('ix_exercises_primary_muscle'), 'exercises', ['primary_muscle'], unique=False)
    op.create_table('workout_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('routine_tag', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_volume_kg', sa.Float(), nullable=True),
    sa.Column('calories_burned', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('in_progress', 'completed', 'skipped', name='session_status_enum'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_logs_id'), 'workout_logs', ['id'], unique=False)
    op.create_index(op.f('ix_workout_logs_user_id'), 'workout_logs', ['user_id'], unique=False)
    op.create_table('workout_exercise_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workout_log_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('sets_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_rest_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['workout_log_id'], ['workout_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_exercise_logs_exercise_id'), 'workout_exercise_logs', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_workout_exercise_logs_id'), 'workout_exercise_logs', ['id'], unique=False)
    op.create_index(op.f('ix_workout_exercise_logs_workout_log_id'), 'workout_exercise_logs', ['workout_log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_exercise_logs_workout_log_id'), table_name='workout_exercise_logs')
    op.drop_index(op.f('ix_workout_exercise_logs_id'), table_name='workout_exercise_logs')
    op.drop_index(op.f('ix_workout_exercise_logs_exercise_id'), table_name='workout_exercise_logs')
    op.drop_table('workout_exercise_logs')
    op.drop_index(op.f('ix_workout_logs_user_id'), table_name='workout_logs')
    op.drop_index(op.f('ix_workout_logs_id'), table_name='workout_logs')
    op.drop_table('workout_logs')
    op.drop_index(op.f('ix_exercises_primary_muscle'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_name'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_id'), table_name='exercises')
    op.drop_table('exercises')
    # ### end Alembic commands ###
